CREATE DATABASE CARS;
 USE CARS;
 -- READ DATA --
 SELECT* FROM car_dekho;
 
 -- TOTAL CARS: TO GET A COUNT OF TOTAL RECORDS --
 SELECT COUNT(*) FROM car_dekho;
 
 -- THE MANGER ASKED EMPOLYEES HOW MANY CARS WILL BE AVIALABLE IN 2023? --
 SELECT COUNT(*) FROM car_dekho
 WHERE YEAR = 2023;
 
  -- THE MANGER ASKED EMPOLYEES HOW MANY CARS WILL BE AVIALABLE IN 2020,2021,2022 --
 SELECT COUNT(*) FROM car_dekho
 WHERE YEAR IN (2020, 2021, 2022)
 GROUP BY YEAR;
 
 -- CLIENT ASKED ME TO PRINT TOTAL OF ALL CARS BY YEAR --
 SELECT YEAR, COUNT(*)FROM car_dekho
GROUP BY YEAR;

-- CLIENT ASKED CAR DEALER AGENT HOW MANY DISEL CARS WILL BE THERE IN 2020 --
SELECT fuel , COUNT(*) FROM car_dekho
WHERE fuel  = "diesel"
AND year = 2020;

-- CLIENT ASKED CAR DEALER AGENT HOW MANY PETROL CARS WILL BE THERE IN 2020 --
SELECT year , COUNT(*) FROM car_dekho
WHERE fuel  = "petrol"
GROUP BY year ; 

-- THE MANAGER TOLD THE EMPLOYEE TO GIVE A PRINT OF ALL FUEL CARS BY YEAR --
SELECT year , COUNT(*) FROM car_dekho
WHERE fuel  = "petrol"
GROUP BY year ; 
SELECT year , COUNT(*) FROM car_dekho
WHERE fuel  = "diesel"
GROUP BY year ; 
SELECT year , COUNT(*) FROM car_dekho
WHERE fuel  = "cng"
GROUP BY year ; 

-- MANAGER SAID THERE WERE MORE THAN 100 CARS IN GIVEN YEAR , WHICH YEAR HAVE MORE THAN 100 CARS?--
SELECT year ,COUNT(*) FROM car_dekho
GROUP BY year 
HAVING COUNT(*)> 100;

-- MANAGER SAID TO GIVE A PRINT OF ALL CARS COUNT BETWEEN 2015 AND 2023 --
SELECT COUNT(*) FROM car_dekho
WHERE YEAR BETWEEN 2015 AND 2023;











 
 